- src/components/Results/Results.tsx
- src/pages/api/clinical-trial-search.ts
- src/pages/results.tsx
- src/queries/clinicalTrialSearchQuery.ts
Changes:
* If there are any errors returned from the search query, there will be a Snackbar that pops up that tells you which services failed.
> Pop up snackbar with error message

- package.json
- src/components/SearchForm/FormFields.tsx
- yarn.lock
```
react-dom.development.js?61bb:67 
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
at Controller (webpack-internal:///./node_modules/react-hook-form/dist/index.esm.js:307:37)
at label
at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-1c22787f.browser.esm.js:55:66)
at FormControlLabel (webpack-internal:///./node_modules/@mui/material/FormControlLabel/FormControlLabel.js:103:80)
at div
at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-1c22787f.browser.esm.js:55:66)
at Stack (webpack-internal:///./node_modules/@mui/material/Stack/Stack.js:117:84)
at …
```
> Fix potential memory leak

- src/components/Results/Study.tsx
- src/components/Results/StudyDetailsButton.tsx
- src/components/Results/StudyHeader.tsx
- src/components/Results/utils.ts
- src/pages/results.tsx
- src/utils/__tests__/distanceUtils.test.ts
- src/utils/distanceUtils.ts
https://user-images.githubusercontent.com/33106214/153697297-f023e525-5bdb-49b4-bf48-4e4ec59b6362.mov
https://user-images.githubusercontent.com/33106214/153697295-719b7615-7b8d-404b-975f-0cfd405c91c7.mov
> Display a study's top 5 closest facilities in an accordion

- src/components/Results/Study.tsx
- src/components/Results/StudyDetailsButton.tsx
https://user-images.githubusercontent.com/33106214/151437227-8fe89e3b-3ed0-4df3-806b-3ae9a3c56f1a.mov
https://user-images.githubusercontent.com/33106214/151437240-550231e2-3714-481d-8d48-94edcf92d2af.mov
> Add clinicaltrials.gov link to More Info button and adjust Study accordion table spacing on XL screens

- src/pages/api/clinical-trial-search.ts
> Eliminate duplicate trials from multiple matching services

- jest.setup.js
- next.config.js
- src/components/SearchForm/MatchingServices.tsx
- src/components/SearchForm/__tests__/SearchForm.test.tsx
- src/components/SearchForm/types.ts
- src/components/Sidebar/Sidebar.tsx
- src/pages/api/clinical-trial-search.ts
- src/queries/clinicalTrialSearchQuery.ts
Changes made
* Moved matching services configuration from SearchForm component and search query into Next.js config file
> Pull out environment variable configuration for matching services

- .eslintignore
- scripts/.gitignore
- scripts/README.md
- scripts/install.js
- scripts/install.ps1
- scripts/install.sh
- scripts/test.js
- scripts/wrappers.json
This adds a bunch of scripts designed to automate installing the system within a fresh server install.
> Add install/test scripts

- src/components/SearchForm/SearchForm.tsx
- src/utils/distanceUtils.ts
- src/utils/exportSearch.ts
- src/utils/fhirConversionUtils.ts
* Compares current search form with default values.
* Indicates in patient bundle whether a field was manually added ("Manually Adjusted")
> Manually adjusted

- src/assets/optimizedPatientDataElements/cancerTypes.json
Fixes some of the SNOMED codes for some primary cancer conditions.
> Code fixes

- README.md
- src/components/Results/Study.tsx
- src/components/Results/StudyContact.tsx
- src/pages/_app.tsx
- src/utils/fhirConversionUtils.ts
Check if the contact is null when rendering it to avoid a null point error on the results page.
> Check null contact

- scripts/README.md
- scripts/install.js
- scripts/install.ps1
- scripts/install.sh
- scripts/test.js
- scripts/test.ps1
- scripts/zip.js
This makes several updates to the install scripts to hopefully make them easier to use.
- Update dependency versions
- Fix issue checking if node_modules is up to date
- Move install.js into pulled files
- Use existing directory when run from existing install
> Update install scripts

- .env
- next.config.js
- package-lock.json
- package.json
- scripts/install.ps1
- scripts/zip.js
- server.js
This contains a bunch of minor fixes:
- Adds the "-NoNetwork" flag to the PowerShell install script so that it can be passed to the Node.js install script
- Fixes formatting to the ZIP file creation script
- Removes the "chai" dev dependency as it is never used (all other dependencies should be in use somewhere)
- Adds the missing second "r" in "rubric" in a few places
- Outputs the configuration being used on app startup to make it easier to verify configuration is being loaded correctly
> Minor fixes

- package-lock.json
- src/components/SearchForm/SearchForm.tsx
Fixes the ZIP code and travel distance fields not being disabled when configured to be disabled.
> Fix location field disable

- .env
- .env.development
- scripts/README.md
- scripts/install.sh
- scripts/wrappers.json
- scripts/zip.js
This removes Ancora from the install script and the default configuration.
> Remove Ancora from installed wrappers

- src/utils/fhir/__tests__/fetch.test.ts
- src/utils/fhir/fetch.ts
- src/utils/sandbox/fetchPatientData.ts
Adds basic sorting by the effectiveDateTime field.
> Add basic sorting by date

- src/utils/sandbox/__tests__/fetchDatientData.test.ts
This doesn't add any new features, merely adds some tests.
> Add tests to verify biomarkers are pulled

- src/pages/api/clinical-trial-search.ts
Removing Ancora specific section from `clinical-trial-search.ts`
> Removing Ancora references

- src/assets/optimizedPatientDataElements/surgeries.json
* Added surgeries for prostate given to us from Pilot test sites.
> Add prostate surgeries

- src/__mocks__/bundles.ts
- src/utils/__tests__/fhirConversionUtils.test.ts
Adds new tests to ensure biomarkers without proper qualifier values are filtered out
> Add testing for qualifiers on biomarkers

- .dockerignore
- .env.production
- Dockerfile
- compose.yml
- docker/app.Dockerfile
- next.config.js
- package-lock.json
- server.js
- src/pages/api/clinical-trial-search.ts
- src/utils/fhir/fetch.ts
Add Docker container configuration files that allow the app and BCT wrapper to be run via a Docker container.
> Add Docker container configuration

- scripts/test.js
Adds the ability to log more data should something go wrong. Uses Node's logging features so extra logging is by default disabled. Enable via:
macOS:
```sh
NODE_DEBUG=CTMS ./scripts/test.js
```
Windows in PowerShell:
```powershell
$Env:NODE_DEBUG = "CTMS"
node scripts\test.js
```
> Add logging statements for debugging

- scripts/test.js
The PR does two things:
- Adds a `--port` argument for specifying the port (required to test against the server in dev mode). (Currently there is no way to test against the wrappers running in dev mode, but that was never really the intention of the script anyway.)
- Ensures that the body of a request is consumed for a redirect (otherwise, the request can hang, waiting for the request body to be read).
> Add --port, consume redirect body (avoids hanging)

- src/pages/api/clinical-trial-search.ts
Resolved and issue where if siteRubic = site2 and cancer type was brain the application would hang.
> Resolve brain hanging

- scripts/README.md
Updates the script README to include the `zip.js` script and how to install and use it.
> Update README to include zip.js
